name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
#    - name: Login to docker hub
#      run: docker login $DOCKER_IMAGE $DOCKER_TOKEN
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dvjhwf8qp/lanbuntu:$(date +%s)
    - name: Push the Docker image
      run: docker push dvjhwf8qp/lanbuntu:latest
